name: C Build and Test

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get install gcc

      - name: Build
        run: gcc -o login login.c

      - name: Run Tests
        run: ./login
