name: C Tests

on:
  push:
    branches:
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get install gcc

      - name: Compile Code
        run: gcc -o output *.c

      - name: Run Tests
        run: ./output
